services:
  # Our PostgreSQL database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!
#      POSTGRES_INITDB_ARGS: "--locale=C.UTF-8"

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080